# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: pt-BR

reviews:
  # Habilitar review automático
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  # Configurações de review
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  # Ignorar arquivos
  path_filters:
    - "!**/*.lock"
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/dist/**"
    - "!**/*.min.js"
    - "!**/*.min.css"

  # Configurações de linguagem
  path_instructions:
    - path: "**/*.ts"
      instructions: |
        - Verificar uso de TypeScript strict (sem any)
        - Verificar imports corretos
        - Verificar tratamento de erros
    - path: "**/*.tsx"
      instructions: |
        - Verificar uso de "use client" quando necessário
        - Verificar props tipadas
        - Verificar acessibilidade básica
    - path: "**/routers/*.ts"
      instructions: |
        - Verificar uso de tenantProcedure para dados multi-tenant
        - Verificar validação com Zod
        - Verificar tratamento de erros

chat:
  auto_reply: true

# Ferramentas de análise
tools:
  eslint:
    enabled: true
  biome:
    enabled: false
  
# Configurações de early access
early_access: false
