import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Coverage reports (generated by Vitest)
    "coverage/**",
  ]),
  {
    rules: {
      // Desabilitar regra que proíbe setState em useEffect
      // É um padrão válido para sincronizar estado com dados externos (queries, localStorage)
      "react-hooks/set-state-in-effect": "off",
      // Indentação: 2 espaços, nunca tabs
      "indent": ["warn", 2, { "SwitchCase": 1 }],
      // Proibir mistura de espaços e tabs
      "no-mixed-spaces-and-tabs": "error",
    },
  },
]);

export default eslintConfig;
