import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Coverage reports (generated by Vitest)
    "coverage/**",
  ]),
  {
    rules: {
      // Desabilitar regra que proíbe setState em useEffect
      // É um padrão válido para sincronizar estado com dados externos (queries, localStorage)
      "react-hooks/set-state-in-effect": "off",
      // Indentação: 2 espaços, nunca tabs
      "indent": ["warn", 2, { "SwitchCase": 1 }],
      // Proibir mistura de espaços e tabs
      "no-mixed-spaces-and-tabs": "error",
    },
  },
  // VIO-984: Design System - Proibir elementos HTML nativos em favor dos componentes do DS
  // Aplicado em src/app (páginas), exceto portais públicos que usam HTML nativo intencionalmente
  {
    files: ["src/app/**/*.tsx", "src/app/**/*.jsx"],
    ignores: ["src/app/portal/**", "src/app/admission/portal/**"],
    rules: {
      "react/forbid-elements": ["warn", {
        "forbid": [
          { "element": "button", "message": "Use <Button> from @/components/ui/Button" },
          { "element": "input", "message": "Use <Input> from @/components/ui/Input" },
          { "element": "select", "message": "Use <Select> from @/components/ui/Select or <NativeSelect> from @/components/ui/NativeSelect" },
          { "element": "textarea", "message": "Use <Textarea> from @/components/ui/Textarea" },
        ]
      }],
    },
  },
  // Permitir variáveis com prefixo _ como não-utilizadas (padrão de destructuring)
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", {
        "argsIgnorePattern": "^_",
        "varsIgnorePattern": "^_",
        "destructuredArrayIgnorePattern": "^_",
      }],
    },
  },
  // ImageUpload usa <img> intencionalmente (preview de upload, não otimizável via next/image)
  {
    files: ["src/components/ui/ImageUpload.tsx"],
    rules: {
      "@next/next/no-img-element": "off",
    },
  },
]);

export default eslintConfig;
